OBJS += drivers/modules/nrf24l01/nrf24l01_soft_driver/nrf24.o
OBJS += drivers/modules/nrf24l01/nrf24l01_soft_driver/nrf24l01_soft_driver.o
OBJS += drivers/modules/nrf24l01/nrf24l01_soft_driver/nrf24.o
OBJS += drivers/modules/nrf24l01/nrf24l01_soft_driver/gateway/radioPinFunctions.o
